# Generated by Django 4.2.4 on 2023-08-13 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Knowledge_Quiz", "0002_quizresult"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizresult",
            old_name="date_taken",
            new_name="timestamp",
        ),
    ]
